### PR TITLE
feat: updated structs, RequestVote RPC, Raft Start

### PR DESCRIPTION
**Pull request by jimil749**
Just opening a PR, so that it is easier to review

### CODE REVIEW

**Comment by jimil749** [comment]
Hmm, the lab2A tests are failing! Looking into it.

**Comment by jimil749** [comment]
Okay, so the test 2A should be fine now! 👍🏻

**Comment by jimil749** [comment]
@yashrajkakkad I think there's a race condition somewhere, other than the tests pass. (running `go test` without `-race` flag works fine)

**Comment by yashrajkakkad** [comment]
@jimil749 Thanks for pointing that out. Made a small fix in `SendAppendEntries`.

**Comment by jimil749** [comment]
Great!

**Pull request merged**
